# PROJECT DIRS
IDIRS:=. CMSIS STM32F4xx_HAL_Driver/Inc

# PROJECT FILES
ARC:=lib$(notdir $(realpath .)).a
STARTUP:=startups/startup_stm32f407xx.S

# TARGET
TARGET:=-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -fsingle-precision-constant

# TOOLCHAIN
TOOLCHAIN:=arm-none-eabi-
CC     :=$(TOOLCHAIN)gcc
CXX    :=$(TOOLCHAIN)g++
ASMC   :=$(TOOLCHAIN)gcc
LD     :=$(TOOLCHAIN)g++
AR     :=$(TOOLCHAIN)ar
OBJCOPY:=$(TOOLCHAIN)objcopy
OBJDUMP:=$(TOOLCHAIN)objdump
SIZE   :=$(TOOLCHAIN)size
STRIP  :=$(TOOLCHAIN)strip

# COMPILER FLAGS
WARNING     :=-Wall -Wextra -pedantic -Wno-implicit-function-declaration
OPTIMIZATION:=-fdata-sections -ffunction-sections -fno-exceptions
